// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/process": {
            "post": {
                "description": "Recebe um texto bruto fatiado por delimitador e/ou um currículo em formato PDF/documento em base64. Identifica compatibilidade de vagas com Gemini e dispara notificações via e-mail e whatsapp.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Processador"
                ],
                "summary": "Processa texto e currículos com match inteligente e envios automáticos",
                "parameters": [
                    {
                        "description": "Payload de processamento",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ProcessRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ProcessResult"
                        }
                    },
                    "400": {
                        "description": "Requisição inválida (JSON corrompido, campos obrigatórios ausentes)",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor ao processar o payload",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Detailed error message here"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "domain.FileMetadata": {
            "type": "object",
            "properties": {
                "mime_type": {
                    "type": "string"
                },
                "size_in_bytes": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "domain.Match": {
            "type": "object",
            "properties": {
                "contact_target": {
                    "description": "email address or phone number",
                    "type": "string"
                },
                "contact_type": {
                    "description": "\"email\" or \"whatsapp\"",
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "domain.ProcessRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "delimiter": {
                    "type": "string"
                },
                "file_base64": {
                    "type": "string"
                }
            }
        },
        "domain.ProcessResult": {
            "type": "object",
            "properties": {
                "bytes_processed": {
                    "type": "integer"
                },
                "duration_ms": {
                    "type": "integer"
                },
                "file": {
                    "$ref": "#/definitions/domain.FileMetadata"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "items_processed": {
                    "type": "integer"
                },
                "matches": {
                    "description": "matches detected by Gemini",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Match"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API Go de Processamento de Texto e Documentos",
	Description:      "API REST para processamento de textos, análise de currículos e disparos automáticos.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
